'use strict';
// Local drafts: publication stays with the owner's existing GitHub workflow.
let draftDB=null,baseSignature='',saveTimer=0,saveQueue=Promise.resolve(),processing=false,revision=0;
const draftStatus=document.createElement('p');draftStatus.className='draft-status';draftStatus.setAttribute('role','status');document.querySelector('header').after(draftStatus);
const dateField=document.createElement('div');dateField.className='field';dateField.innerHTML='<label for="dateBasis">Что означает дата</label><select id="dateBasis"><option value="work_year">Выполнение работ</option><option value="publication_year">Архивная публикация</option></select>';$('completedAt').parentElement.after(dateField);
const previewButton=document.createElement('button');previewButton.type='button';previewButton.className='btn';previewButton.textContent='Предпросмотр';document.querySelector('.bottom').prepend(previewButton);
const previewDialog=document.createElement('dialog');previewDialog.className='object-preview';document.body.append(previewDialog);
function validDate(s){if(!s)return true;if(!/^\d{4}(?:-\d{2}(?:-\d{2})?)?$/.test(s))return false;const [y,m,d]=s.split('-').map(Number);return y>=1900&&y<=2100&&(!m||m<=12)&&(!s.includes('-')||m>=1)&&(d===undefined||(d>=1&&d<=new Date(y,m,0).getDate()));}
function readFields(){const o=objectById();if(!o)return;for(const k of ['title','region','city','completedAt','coating','description'])o[k]=clean($(k).value);o.dateBasis=$('dateBasis').value;}
function dbPut(value,key='current'){return new Promise((resolve,reject)=>{const tx=draftDB.transaction('drafts','readwrite');tx.objectStore('drafts').put(value,key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error);tx.onabort=()=>reject(tx.error||Error('Запись прервана'));});}
function dbGet(key){return new Promise((resolve,reject)=>{const req=draftDB.transaction('drafts').objectStore('drafts').get(key);req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}
function persist(){clearTimeout(saveTimer);if(!draftDB){draftStatus.textContent='Автосохранение недоступно. Скачайте ZIP перед закрытием страницы.';return Promise.resolve();}const savedRevision=revision;const snapshot={items:clone(items),pending:[...pending],selectedId,baseSignature,savedAt:Date.now()};saveQueue=saveQueue.catch(()=>{}).then(()=>dbPut(snapshot)).then(()=>{if(savedRevision===revision){draftStatus.textContent='Черновик сохранён на этом устройстве · сайт обновляется после публикации ZIP';dirty=false;}}).catch(e=>{dirty=true;draftStatus.textContent='Не удалось сохранить черновик. Скачайте ZIP. '+(e.name==='QuotaExceededError'?'Закончилось место в браузере.':'');});return saveQueue;}
function changed(){revision++;dirty=true;draftStatus.textContent='Сохраняем черновик…';clearTimeout(saveTimer);saveTimer=setTimeout(persist,400);}
const oldOpen=openObject;
openObject=function(id){oldOpen(id);$('dateBasis').value=objectById()?.dateBasis||'work_year';};
const oldAdd=addObject;addObject=function(){oldAdd();changed();};$('addBtn').onclick=addObject;
$('form').addEventListener('input',()=>{readFields();changed();});
$('form').addEventListener('change',()=>{readFields();changed();});
saveForm=function(e){e?.preventDefault();readFields();const o=objectById();if(!o)return false;if(!o.title||!o.region||!validDate(o.completedAt)){toast('Укажите название, регион и корректную дату (или оставьте дату пустой).','error');return false;}renderList();changed();persist();toast('Изменения внесены. Статус сохранения — над формой. Для публикации скачайте ZIP.');return true;};$('form').onsubmit=saveForm;
const oldDelete=deleteObject;deleteObject=function(){oldDelete();changed();};$('deleteBtn').onclick=deleteObject;
function photoURL(path){return previewUrls.get(path)||path;}
function movePhoto(o,from,to){if(to<0||to>=o.photos.length)return;for(const key of ['photos','photoVariants','photoFrames']){if(!o[key])continue;while(o[key].length<o.photos.length)o[key].push(null);const [v]=o[key].splice(from,1);o[key].splice(to,0,v);}renderPhotos();changed();}
renderPhotos=function(){const o=objectById();if(!o)return;$('photoCount').textContent=`${o.photos.length} фото`;$('photos').innerHTML=o.photos.map((p,i)=>`<div class="photo"><img src="${esc(photoURL(o.photoVariants?.[i]?.[0]?.src||p))}" loading="lazy" alt="Фото ${i+1}"><div class="photo-actions"><button type="button" data-cover="${i}" ${i===0?'disabled':''}>${i===0?'Обложка':'На обложку'}</button><button type="button" data-left="${i}" ${i===0?'disabled':''} aria-label="Фото ${i+1}: переместить влево">←</button><button type="button" data-right="${i}" ${i===o.photos.length-1?'disabled':''} aria-label="Фото ${i+1}: переместить вправо">→</button><button type="button" data-remove="${i}" aria-label="Удалить фото ${i+1}">Удалить</button></div></div>`).join('');$('photos').querySelectorAll('[data-cover]').forEach(b=>b.onclick=()=>movePhoto(o,+b.dataset.cover,0));$('photos').querySelectorAll('[data-left]').forEach(b=>b.onclick=()=>movePhoto(o,+b.dataset.left,+b.dataset.left-1));$('photos').querySelectorAll('[data-right]').forEach(b=>b.onclick=()=>movePhoto(o,+b.dataset.right,+b.dataset.right+1));$('photos').querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{const i=+b.dataset.remove;if(!confirm(`Удалить фото ${i+1} из карточки?`))return;for(const key of ['photos','photoVariants','photoFrames'])o[key]?.splice(i,1);renderPhotos();changed();});};
async function resized(bmp,max,quality){const c=document.createElement('canvas'),scale=Math.min(1,max/Math.max(bmp.width,bmp.height));c.width=Math.max(1,Math.round(bmp.width*scale));c.height=Math.max(1,Math.round(bmp.height*scale));c.getContext('2d').drawImage(bmp,0,0,c.width,c.height);const blob=await new Promise((res,rej)=>c.toBlob(b=>b?res(b):rej(Error('Ошибка обработки')),'image/webp',quality));return {blob,width:c.width,height:c.height};}
addPhotos=async function(files){const o=objectById();if(!o||processing)return;processing=true;$('exportBtn').disabled=true;$('photoInput').disabled=true;let failures=[],added=0;toast('Готовим оригиналы и превью…');try{for(const file of files){let bmp;try{if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Нужен JPEG, PNG или WebP');if(file.size>40*1024*1024)throw Error('Фото больше 40 МБ');bmp=await createImageBitmap(file);const key=uniqueId(),ext={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'}[file.type],path=`assets/manual/${key}.${ext}`,variants=[];const staged=[[path,file]];for(const max of [480,960]){const r=await resized(bmp,max,max===480?.82:.88),src=`assets/manual/${key}-${max}.${r.blob.type==='image/webp'?'webp':'png'}`;staged.push([src,r.blob]);variants.push({src,width:r.width,height:r.height});}for(const [p,b] of staged){pending.set(p,b);previewUrls.set(p,URL.createObjectURL(b));}o.photoVariants??=o.photos.map(()=>null);o.photos.push(path);o.photoVariants.push(variants.filter((v,i,a)=>a.findIndex(x=>x.width===v.width)===i));if(o.photoFrames)o.photoFrames.push(null);added++;}catch(e){failures.push(file.name+': '+e.message);}finally{bmp?.close();}}}finally{processing=false;$('photoInput').disabled=false;$('exportBtn').disabled=false;if(selectedId===o.id)renderPhotos();changed();await persist();toast(`Добавлено: ${added}.`+(failures.length?' Не загружено: '+failures.join('; '):''),failures.length?'error':'ok');}};
$('photoInput').accept='image/jpeg,image/png,image/webp';
function preview(){readFields();const o=objectById();if(!o)return;previewDialog.replaceChildren();const close=document.createElement('button');close.className='btn';close.textContent='Закрыть предпросмотр';close.onclick=()=>previewDialog.close();const heading=document.createElement('h2');heading.textContent=o.title||'Без названия';const meta=document.createElement('p');meta.textContent=[o.region,o.city,(o.dateBasis==='publication_year'?'Публикация: ':'Работы: ')+(o.completedAt||'дата уточняется'),o.coating].filter(Boolean).join(' · ');previewDialog.append(close,heading,meta);for(const p of o.photos){const img=document.createElement('img');img.src=photoURL(p);img.alt=o.title;img.loading='lazy';previewDialog.append(img);}const desc=document.createElement('p');desc.style.whiteSpace='pre-wrap';desc.textContent=o.description;previewDialog.append(desc);previewDialog.showModal();}
previewButton.onclick=preview;
// Preserve all fields, including crops, original dates and provenance.
strip=o=>clone(o);
exportUpdate=async function(){if(processing)return;readFields();const invalid=items.find(o=>!clean(o.title)||!o.region||!validDate(o.completedAt));if(invalid){openObject(invalid.id);toast('Заполните название и регион; исправьте дату или оставьте её пустой.','error');return;}try{$('exportBtn').disabled=true;await persist();const used=new Set(items.flatMap(o=>[...o.photos,...(o.photoVariants||[]).flatMap(v=>(v||[]).map(x=>x.src))]));const assets=[...pending].filter(([p])=>used.has(p));if(assets.reduce((s,[,b])=>s+b.size,0)>500*1024*1024)throw Error('Пакет новых фото больше 500 МБ. Опубликуйте меньшими частями.');const guide='Распакуйте ZIP в папку сайта с заменой файлов. GitHub Desktop: Commit → Push origin. Это полный objects.json, не объединяйте его с параллельными правками другого устройства. После публикации откройте мастерскую и начните с опубликованной базы. Оригиналы новых фото включены в архив.';const entries=[{name:'objects.json',data:new TextEncoder().encode(JSON.stringify(items.map(strip),null,2))},{name:'UPDATE.txt',data:new TextEncoder().encode(guide)},...assets.map(([name,data])=>({name,data}))];const zip=await makeZip(entries),a=document.createElement('a'),url=URL.createObjectURL(zip);a.href=url;a.download=`ARDMAN_UPDATE_${new Date().toISOString().slice(0,10)}.zip`;a.click();setTimeout(()=>URL.revokeObjectURL(url),60000);toast('ZIP скачан. Для обновления сайта опубликуйте его через GitHub Desktop.');}catch(e){toast(e.message,'error');}finally{$('exportBtn').disabled=false;}};$('exportBtn').onclick=exportUpdate;
document.addEventListener('visibilitychange',()=>{if(document.hidden&&dirty)persist();});
const reset=document.createElement('button');reset.className='btn';reset.textContent='Начать с опубликованной базы';document.querySelector('.head-actions').append(reset);
reset.onclick=async()=>{if(!confirm('Открыть опубликованную базу? Текущий черновик будет сохранён как предыдущий. Скачайте ZIP, если он ещё нужен.'))return;try{clearTimeout(saveTimer);await saveQueue;if(draftDB){await dbPut({items:clone(items),pending:[...pending],baseSignature},'previous');await dbPut(null);}dirty=false;location.reload();}catch{toast('Не удалось сохранить предыдущий черновик. Сначала скачайте ZIP.','error');}};
async function bootWorkshop(){$('addBtn').disabled=true;await init();if(!items.length){draftStatus.textContent='База не загружена. Обновите страницу перед редактированием.';return;}$('addBtn').disabled=false;baseSignature=JSON.stringify(items);try{draftDB=await new Promise((resolve,reject)=>{const r=indexedDB.open('ardman-workshop-v5',1);r.onupgradeneeded=()=>r.result.createObjectStore('drafts');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const draft=await dbGet('current');if(draft?.items){let restore=true;if(draft.baseSignature!==baseSignature)restore=confirm('Опубликованная база изменилась. Восстановить ваш локальный черновик? Он может не содержать последних изменений сайта. Отмена — открыть опубликованную базу, сохранив старый черновик как предыдущий.');if(restore){items=draft.items;for(const [p,b] of draft.pending||[]){pending.set(p,b);previewUrls.set(p,URL.createObjectURL(b));}baseSignature=draft.baseSignature;fillRegions();renderList();if(draft.selectedId&&items.some(o=>o.id===draft.selectedId))openObject(draft.selectedId);draftStatus.textContent='Восстановлен локальный черновик. Он ещё не опубликован.';}else{await dbPut(draft,'previous');await dbPut(null);draftStatus.textContent='Открыта опубликованная база. Предыдущий черновик сохранён.';}}else draftStatus.textContent='Мастерская готова. Черновик будет сохраняться в этом браузере.';}catch{draftStatus.textContent='Автосохранение недоступно. Скачайте ZIP перед закрытием страницы.';}}
const restorePrevious=document.createElement('button');restorePrevious.className='btn';restorePrevious.textContent='Предыдущий черновик';document.querySelector('.head-actions').append(restorePrevious);restorePrevious.onclick=async()=>{if(!draftDB)return toast('Хранилище браузера недоступно','error');const previous=await dbGet('previous');if(!previous)return toast('Предыдущего черновика нет');if(!confirm('Восстановить предыдущий черновик? Сначала скачайте текущие правки, если они нужны.'))return;clearTimeout(saveTimer);await saveQueue;await dbPut(previous);dirty=false;location.reload();};
bootWorkshop();
